package managmentsystem;

import com.mysql.jdbc.Connection;
import java.awt.ComponentOrientation;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javafx.scene.control.ComboBox;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class addpatient extends javax.swing.JFrame {

    String name;
    int id,uid;
    ;
    //ComboBoxModel<String> model;
    public addpatient() {
        initComponents();
    }
    
    public addpatient(String name, int id) 
    {
        initComponents();
        this.name = name;
        this.id = id;
        
      //   model = doctors.getModel();
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbladdpatient = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblname = new javax.swing.JLabel();
        lblcontactno = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        lblbill = new javax.swing.JLabel();
        lbldoctor = new javax.swing.JLabel();
        txtbill = new javax.swing.JTextField();
        doctors = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Receipt = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblreciept = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        spciality = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(888, 534));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbladdpatient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbladdpatient.setText("ADD PATIENT");
        jPanel1.add(lbladdpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 29, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 65, 167, 10));

        lblname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblname.setText("NAME :");
        jPanel1.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 108, -1, -1));

        lblcontactno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcontactno.setText("Contact No: ");
        jPanel1.add(lblcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 171, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Address :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 101, 236, 35));
        jPanel1.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 163, 236, 35));

        txtaddress.setColumns(20);
        txtaddress.setLineWrap(true);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 236, 64));

        lblbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblbill.setText("Bill :");
        jPanel1.add(lblbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 42, -1));

        lbldoctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldoctor.setText("Doctor :");
        jPanel1.add(lbldoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));
        jPanel1.add(txtbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 236, 35));

        doctors.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        doctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorsActionPerformed(evt);
            }
        });
        jPanel1.add(doctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 236, 35));

        Receipt.setEditable(false);
        Receipt.setBackground(new java.awt.Color(204, 204, 204));
        Receipt.setColumns(20);
        Receipt.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        Receipt.setRows(5);
        jScrollPane2.setViewportView(Receipt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 360, 520));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managmentsystem/Close.png"))); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, -1, 39));

        btnclear.setBackground(new java.awt.Color(255, 51, 51));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managmentsystem/Close.png"))); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, -1, 39));

        jButton4.setBackground(new java.awt.Color(51, 102, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managmentsystem/save-icon--1.png"))); // NOI18N
        jButton4.setText("SAVE");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 177, 39));

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managmentsystem/print.png"))); // NOI18N
        jButton3.setText("PRINT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 177, 39));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 120, 10, 480));

        lblreciept.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblreciept.setText("RECIEPT");
        jPanel1.add(lblreciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 72, 110, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Speciality :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        spciality.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        spciality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family Physician", "Gynecologist", "Surgeon", "Psychiatrist", "Cardiologist", "Dermatologist", "Infectious Disease Physician", "Ophthalmologist", "Pulmonologist", "Neurologist", "Physician Executive", "Radiologist", "Oncologist", "Anesthesiologist" }));
        spciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spcialityActionPerformed(evt);
            }
        });
        spciality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spcialityKeyReleased(evt);
            }
        });
        jPanel1.add(spciality, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 236, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Age");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Gender");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        male.setText("Male");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        female.setText("Female");
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        buttonGroup1.add(other);
        other.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        other.setText("Other");
        jPanel1.add(other, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new reception(name, id).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        register();
        receipt();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void doctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorsActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtname.setText("");
        txtaddress.setText("");
        txtcontact.setText("");
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name = txtname.getText();        
        String contact = txtcontact.getText();
        String address = txtaddress.getText();
        String Bill = txtbill.getText();
        if (name.trim().isEmpty() || contact.trim().isEmpty() || address.trim().isEmpty() || Bill.trim().isEmpty())
        {
            JOptionPane.showMessageDialog(addpatient.this, "Fields can't be empty");
        }
        else
        {
        try {
            Receipt.print();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void spcialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spcialityActionPerformed
        String speciality = (String) spciality.getSelectedItem();
        
        adddoctors(speciality);
        
    }//GEN-LAST:event_spcialityActionPerformed

    private void spcialityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spcialityKeyReleased
        String speciality = (String) spciality.getSelectedItem();
        
        adddoctors(speciality);
// TODO add your handling code here:
    }//GEN-LAST:event_spcialityKeyReleased
    
    /**
     * @param args the command line arguments
     */
    //registering a patient
    public void register() 
    {
        
        String name = txtname.getText();        
        String contact = txtcontact.getText();
        String address = txtaddress.getText();
        String disease = null;
        String prescribe = null;
        String doctor = (String)doctors.getSelectedItem();
        String gender = gender();
        
        if (name.trim().isEmpty() || contact.trim().isEmpty() || address.trim().isEmpty() || gender == null) {
            JOptionPane.showMessageDialog(addpatient.this, "Fields can't be empty");
        } 
        else {
            try {
                String query = "insert into patient(name, contact, address, disease, prescribe , doctor , Gender) VALUES('"+name+"','"+contact+"','"+address+"','"+disease+"', '" +prescribe+ "' , '"+doctor+"' , '"+gender+"')";
                Db.setData(query);
            } catch (Exception e) {
                System.out.println("" + e.getMessage());
            }
        }

    }
    //it returns the gender selected
    public String gender()
    { 
        String gender = null;
        if (male.isSelected() == true) 
            {
                gender = "male";
            }
        else
            if (female.isSelected() == true) 
            {
                gender = " female";
            }
        else
                if (other.isSelected() == true) 
            {
                gender = "other";
            }
        return gender;
    }
    //it generate reciept
    public void receipt()
    {
        String query = "select id from patient WHERE name = '" +txtname.getText() +"'";
        int Mrno=0;
        String doctor = "";
        try {
            ResultSet rs = Db.getData(query);
            if (rs.next()) {
             
            Mrno = rs.getInt("id");  
            doctor = (String)doctors.getSelectedItem();
            
            }
            } 
        catch (Exception e) {
        }
        Date obj = new Date();
        Receipt.setText   ("*****************************\n");
        Receipt.setText(Receipt.getText() +"*****************************\n");
        Receipt.setText(Receipt.getText() +"\n**      Patient Receipt      **\n");
        Receipt.setText(Receipt.getText() +"Date: "+ obj.toString() +"\n");
        Receipt.setText(Receipt.getText() +"Mr#:" +Mrno +"\n" );
        Receipt.setText(Receipt.getText() +"Name: "+ txtname.getText() +"\n");
        Receipt.setText(Receipt.getText() +"Gender: "+ gender() +"\n");
        Receipt.setText(Receipt.getText() +"Doctor: "+doctor +"\n");
        Receipt.setText(Receipt.getText() +"Bill: "+txtbill.getText() +"\n");
       
        
        
    }
    //adding doctors in combo box
    public void adddoctors(String speciality)
    {
        
        
        doctors.removeAllItems();
        String query = "select * from doctor WHERE speciality = '" +speciality+ "'";
        try {
            ResultSet rs = Db.getData(query);
            
            while(rs.next())
            {
                String name = rs.getString("name");
                
                doctors.addItem(name);
            }
        } catch (Exception e) {
        }
    }
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addpatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Receipt;
    private javax.swing.JButton btnclear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> doctors;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbladdpatient;
    private javax.swing.JLabel lblbill;
    private javax.swing.JLabel lblcontactno;
    private javax.swing.JLabel lbldoctor;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblreciept;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton other;
    private javax.swing.JComboBox<String> spciality;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtbill;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
