package managmentsystem;

public class doctor extends javax.swing.JFrame {

    /**
     * Creates new form doctor
     */
    String name;
    int id;

    public doctor() {
        initComponents();
    }

    public doctor(String name, int id) {
        initComponents();
        this.name = name;
        this.id = id;
        jLabel3.setText(name.toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnviewpatient = new javax.swing.JButton();
        btnviewprescription = new javax.swing.JButton();
        btnchangepassword = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doctor");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DOCTOR");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 175, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 153, 10));

        btnviewpatient.setBackground(new java.awt.Color(255, 153, 0));
        btnviewpatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnviewpatient.setText("Patients");
        btnviewpatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnviewpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewpatientActionPerformed(evt);
            }
        });
        jPanel3.add(btnviewpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 234, 76));

        btnviewprescription.setBackground(new java.awt.Color(255, 153, 0));
        btnviewprescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnviewprescription.setText("Add Prescription");
        btnviewprescription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnviewprescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewprescriptionActionPerformed(evt);
            }
        });
        jPanel3.add(btnviewprescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 220, 76));

        btnchangepassword.setBackground(new java.awt.Color(255, 153, 0));
        btnchangepassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnchangepassword.setText("Change Password");
        btnchangepassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnchangepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangepasswordActionPerformed(evt);
            }
        });
        jPanel3.add(btnchangepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 234, 77));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGOUT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, 45));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME : ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, 36));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ABC");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 260, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();        
        new login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnchangepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangepasswordActionPerformed
        this.dispose();
        new changepassword(name, id, 1).setVisible(true);
    }//GEN-LAST:event_btnchangepasswordActionPerformed

    private void btnviewpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewpatientActionPerformed
        //this.setExtendedState(JFrame.ICONIFIED);
        
        new viewpatient(name, id, 1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnviewpatientActionPerformed

    private void btnviewprescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewprescriptionActionPerformed
        this.dispose();
        new addprescription(name, id).setVisible(true);
    }//GEN-LAST:event_btnviewprescriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchangepassword;
    private javax.swing.JButton btnviewpatient;
    private javax.swing.JButton btnviewprescription;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
