package managmentsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

public class viewdoctor extends javax.swing.JFrame {

    int id;
    String name;

    public viewdoctor() {
        initComponents();
        display();
    }

    public viewdoctor(String name, int id) {
        initComponents();
        display();
        this.name = name;
        this.id = id;
    }

    public void display() {
        String query = "select id, name, contact, address , email  from doctor";
        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/admin", "root", "");
//            PreparedStatement stm = con.prepareStatement(query);
//            ResultSet rs = stm.executeQuery();
            ResultSet rs = Db.getData(query);
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnclose = new javax.swing.JButton();
        btnclose1 = new javax.swing.JButton();
        btnclose2 = new javax.swing.JButton();
        btnclose3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW DOCTOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 266, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managmentsystem/search.png"))); // NOI18N
        jLabel2.setText("Search");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 230, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact", "Address", "Email"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 528, -1));

        btnclose.setBackground(new java.awt.Color(255, 51, 51));
        btnclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclose.setText("Back");
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 107, 34));

        btnclose1.setBackground(new java.awt.Color(255, 51, 51));
        btnclose1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclose1.setText("Delete Dr.");
        btnclose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 107, 34));

        btnclose2.setBackground(new java.awt.Color(255, 51, 51));
        btnclose2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnclose2.setText("Edit/Update Dr.");
        btnclose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 140, 34));

        btnclose3.setBackground(new java.awt.Color(255, 51, 51));
        btnclose3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclose3.setText("Add Dr.");
        btnclose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 107, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 623));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        this.dispose();
        new Admin(name, id).setVisible(true);
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnclose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose1ActionPerformed
        // TODO add your handling code here:       
        String id = JOptionPane.showInputDialog(this, "Id:");
        if (id != null) {
            try {
                String query = "select * from doctor where id = '" + id + "'";
                ResultSet rs = Db.getData(query);
                if (rs.next()) {
                    query = "DELETE FROM doctor WHERE id='" + id + "'";
                    Db.setData(query);
                    JOptionPane.showMessageDialog(null, "Record deleted...");
                    display();
                } else {
                    JOptionPane.showMessageDialog(this, "ID does not exist..");
                }
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            } catch (Exception ex) {
                Logger.getLogger(viewdoctor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnclose1ActionPerformed

    private void btnclose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose2ActionPerformed
        String res = JOptionPane.showInputDialog(this, "Enter ID..");
        String server = "doctor";
        if (res != null) {
            try {
                String query = "select id from doctor where id = '" + res + "'";
                ResultSet rs = Db.getData(query);
                if (rs.next()) {
                    this.dispose();
                    new Editupdatedoctor(name, server, id, Integer.parseInt(res)).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Id does not exists..");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }
        
    }//GEN-LAST:event_btnclose2ActionPerformed

    private void btnclose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose3ActionPerformed
        this.dispose();
        new Adddoctor(name, id).setVisible(true);
    }//GEN-LAST:event_btnclose3ActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        filter(txtsearch.getText().trim());
        
    }//GEN-LAST:event_txtsearchKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)table.getModel();
     int selectedindex = table.getSelectedRow();
     String id = model.getValueAt(selectedindex, 0).toString();
     String name = model.getValueAt(selectedindex, 1).toString();
     String contact = model.getValueAt(selectedindex, 2).toString();
     String address = model.getValueAt(selectedindex, 3).toString();
     String email = model.getValueAt(selectedindex, 4).toString();
     
     
     JOptionPane.showMessageDialog(this,"ID = "+id +" \n"+
                                        "Name = "+name +"\n"+
                                        "contact = "+contact +"\n"+
                                        "Address = "+address +"\n" +
                                        "Email = "+email);
                                       
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    private void filter(String query)
    {
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
                table.setRowSorter(tr);
                tr.setRowFilter(RowFilter.regexFilter(query));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewdoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewdoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewdoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewdoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewdoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnclose1;
    private javax.swing.JButton btnclose2;
    private javax.swing.JButton btnclose3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
