package managmentsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

public class viewpatient extends javax.swing.JFrame {

    /**
     * Creates new form viewpatient
     */
    String name;
    int id;
    int who;

    public viewpatient() {
        initComponents();
        display();
    }

    public viewpatient(String name, int id, int who) {
        initComponents();
        
        this.name = name;
        this.id = id;
        this.who = who;
        if (who == 1) 
                    {
                        display1();
                        btneditpatient.setEnabled(false);
                    }
        else 
            if (who == 0 )
                    {
                        display();
                        btneditpatient.setEnabled(false);
                    }
        else
            if (who == 2) 
                    {
                        display();
                        
                    }
    }
    ResultSet rs;

    public void display() 
    {
        String query = "select id, name, contact, disease, prescribe, address  from patient";
        try {
            rs = Db.getData(query);
            table.setModel(DbUtils.resultSetToTableModel(rs));

            
            
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }

    }
    //method that will be called when a doctor see patients
    public void display1() 
    {
        String query = "select id, name, contact, disease, prescribe, address  from patient WHERE doctor = '" +name+ "'";
        try {
            rs = Db.getData(query);
            table.setModel(DbUtils.resultSetToTableModel(rs));

            
            
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }

    }
    private void filter(String query)
    {
        
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
                table.setRowSorter(tr);
                tr.setRowFilter(RowFilter.regexFilter(query));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btneditpatient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW PATIENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 260, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managmentsystem/search.png"))); // NOI18N
        jLabel2.setText("Search");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, 36));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 230, 36));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managmentsystem/back.png"))); // NOI18N
        jButton2.setText("BACK");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 120, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Patient Detail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact", "Disease", "Prescription", "Address"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 520, 380));

        btneditpatient.setBackground(new java.awt.Color(255, 51, 51));
        btneditpatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btneditpatient.setText("Edit Patient");
        btneditpatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditpatientActionPerformed(evt);
            }
        });
        jPanel1.add(btneditpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 120, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        switch (who) 
        {
            case 0:
                this.dispose();
                new Admin(name, id).setVisible(true);
                break;
            case 1:
                this.dispose();
                new doctor(name, id).setVisible(true);
                break;
            case 2:
                this.dispose();
                new reception(name, id).setVisible(true);
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        filter(txtsearch.getText().trim());
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
     DefaultTableModel model = (DefaultTableModel)table.getModel();
     int selectedindex = table.getSelectedRow();
     String id = model.getValueAt(selectedindex, 0).toString();
     String name = model.getValueAt(selectedindex, 1).toString();
     String contact = model.getValueAt(selectedindex, 2).toString();
     String disease = model.getValueAt(selectedindex, 3).toString();
     String prescription = model.getValueAt(selectedindex, 4).toString();
     
     JOptionPane.showMessageDialog(this,"ID = "+id +" \n"+
                                        "Name = "+name +"\n"+
                                        "contact = "+contact +"\n"+
                                        "Disease = "+disease + "\n"+
                                        "Prescription = "+prescription);
    }//GEN-LAST:event_tableMouseClicked

    private void btneditpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditpatientActionPerformed
        String res = JOptionPane.showInputDialog(this, "Enter ID..");
        
        if (res != null) {
            try {
                String query = "select id from patient where id = '" + res + "'";
                ResultSet rs = Db.getData(query);
                if (rs.next()) {
                    this.dispose();
                    new editpatient(name , id, Integer.parseInt(res)).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Id does not exists..");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }

    }//GEN-LAST:event_btneditpatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewpatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditpatient;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
